Usage: Pymatgen (Python Materials Genomics) 

Official documentation
https://pymatgen.org/

The Material Project Workshop 2021 
https://workshop.materialsproject.org/lessons/02_intro_pymatgen/1%20-%20pymatgen%20foundations/

In [8]:
!pip install numpy
!pip install pymatgen

In [9]:
import pymatgen.core
print('pymatgen Ver.',pymatgen.core.__version__)
print(pymatgen.__file__)

pymatgen Ver. 2022.0.16
None


In [10]:
# check python version
import sys
print(sys.version)

3.7.12 (default, Sep 10 2021, 00:21:48) 
[GCC 7.5.0]


In [12]:
# Import of class Molecule
from pymatgen.core import Molecule

In [13]:
# Check the class description: Shift + Tab
Molecule

pymatgen.core.structure.Molecule

In [14]:
# A molecule is defined by specifying the element and coordinates.
c_monox = Molecule(["C","O"], [[0.0, 0.0, 0.0], [0.0, 0.0, 1.2]])
print(c_monox)

Full Formula (C1 O1)
Reduced Formula: CO
Charge = 0.0, Spin Mult = 1
Sites (2)
0 C     0.000000     0.000000     0.000000
1 O     0.000000     0.000000     1.200000


In [15]:
# Specify a valence in the argument charge to make it an anion
oh_minus = Molecule(["O", "H"], [[0.0, 0.0, 0.0], [0.0, 0.0, 1.0]], charge=-1)
print(oh_minus)

Full Formula (H1 O1)
Reduced Formula: H2O2
Charge = -1, Spin Mult = 1
Sites (2)
0 O     0.000000     0.000000     0.000000
1 H     0.000000     0.000000     1.000000


In [18]:
from google.colab import files
uploaded = files.upload() # *.xyz

Saving H2O.xyz to H2O.xyz


In [19]:
# Read a file in xyz format and create a Molecule object
water = Molecule.from_file("H2O.xyz")
print(water)

Full Formula (H2 O1)
Reduced Formula: H2O
Charge = 0, Spin Mult = 1
Sites (3)
0 O    -0.070000    -0.026960    -0.095240
1 H     0.919330    -0.015310    -0.054070
2 H    -0.359290     0.231000     0.816010


In [20]:
# Save the Molecule object in a xyz format file
c_monox.to(filename="c_monox.xyz")

'2\nC1 O1\nC 0.000000 0.000000 0.000000\nO 0.000000 0.000000 1.200000'

In [21]:
# You can retrieve the attributes of Molecule instance in "c_monox.XXX"
# (Enter "c_monox." And press the "tab key" to see a list of attributes and methods.)
# Cartesian coordinates of each atom
print(c_monox.cart_coords)

[[0.  0.  0. ]
 [0.  0.  1.2]]


In [22]:
# Center of mass (center of gravity)
print(c_monox.center_of_mass)

[0.         0.         0.68544132]


In [23]:
# There are methods for changing the attributes of Molecule instances.
# Change valence
c_monox.set_charge_and_spin(charge=1)
print(c_monox)

Full Formula (C1 O1)
Reduced Formula: CO
Charge = 1, Spin Mult = 2
Sites (2)
0 C     0.000000     0.000000     0.000000
1 O     0.000000     0.000000     1.200000


In [24]:
# Molecule objects are like a list of Sites
# Note: The function len displays the number of elements in the list
len(c_monox)

2

In [25]:
# Information on each site can be retrieved by specifying the index of the list.
print('Site 0:')
print(c_monox[0])
print('Site 1:')
print(c_monox[1])

Site 0:
[0. 0. 0.] C
Site 1:
[0.  0.  1.2] O


In [26]:
# Elements can be replaced by specifying the index
c_monox[0] = "O"
c_monox[1] = "C"
print(c_monox)

Full Formula (C1 O1)
Reduced Formula: CO
Charge = 1, Spin Mult = 2
Sites (2)
0 O     0.000000     0.000000     0.000000
1 C     0.000000     0.000000     1.200000


In [27]:
# Extract the information of the first site (it can be referenced by the variable site0)
site0 = c_monox[0]
print(site0)

[0. 0. 0.] O


In [28]:
# Attribute coords is the coordinates of the atom
site0.coords

array([0., 0., 0.])

In [29]:
# Attribute specie is an element
site0.specie

Element O

In [37]:
# Differences between each class
# Element: Element (on the periodic table),
from pymatgen.core import Element
# Specie: Element plus oxidation status information,
from pymatgen.core.periodic_table import Specie
# Composition: Composition
from pymatgen.core import Composition

In [39]:
# You can create an Element object with a symbol of the periodic table
# (Elemental information is an attribute of the object)
carbon = Element('C')
carbon.average_ionic_radius

0.3

In [40]:
# Create a Specie object by specifying the oxidation state
o_ion = Specie('O', oxidation_state=-2)
o_ion

Species O2-

In [42]:
# Oxidation state
o_ion.oxi_state
o_ion.atomic_mass

15.9994

In [43]:
# You can directly specify the oxidation state using a character string
Specie.from_string('O2-')

Species O2-

In [44]:
# Create an object with a composition of 50% Au and 50% Cu
# (Be careful about the type of parentheses because it is initialized as a dictionary type)
comp = Composition({'Au': 0.5, 'Cu': 0.5})

In [45]:
# The composition formula (formula) and chemical system (chemical system) can be output as a character string.
print("formula", comp.alphabetical_formula)
print("chemical system", comp.chemical_system)

formula Au0.5 Cu0.5
chemical system Au-Cu


Hydrogen Cyanide

In [46]:
# Using the characteristics of the elements, we make an atom consisting of H, C, and N on a straight line.
# (Atomic coordinates were determined as "chemical bond length" = "sum of atomic radii".)
H_rad = Element('H').atomic_radius
C_rad = Element('C').atomic_radius
N_rad = Element('N').atomic_radius
HC_bond_dist = H_rad + C_rad
CN_bond_dist = C_rad + N_rad
H_pos = 0
C_pos = H_pos + HC_bond_dist
N_pos = C_pos + CN_bond_dist
hcn = Molecule(['H','C','N'], [[H_pos, 0, 0], [C_pos, 0, 0],[N_pos, 0, 0]])
print(hcn)

Full Formula (H1 C1 N1)
Reduced Formula: HCN
Charge = 0.0, Spin Mult = 1
Sites (3)
0 H     0.000000     0.000000     0.000000
1 C     0.950000     0.000000     0.000000
2 N     2.300000     0.000000     0.000000


Class Lattice, Class Structure

In [48]:
# Class Structure looks similar to Molecule, except that it adds grid information.
# A class for representing crystal structures
from pymatgen.core import Lattice, Structure

In [49]:
# A lattice is defined using a lattice vector.
# The following means a cubic lattice with a side of 5 Å
my_lattice = Lattice([[5, 0, 0], [0, 5, 0], [0, 0, 5]])
print(my_lattice)

5.000000 0.000000 0.000000
0.000000 5.000000 0.000000
0.000000 0.000000 5.000000


In [50]:
# Also specify the angle between the lattice vectors (same as my_lattice)
my_lattice_2 = Lattice.from_parameters(5, 5, 5, 90, 90, 90)

In [51]:
# Create a Lattice object with the grid shape (cubic in this case) and its parameters
my_lattice_3 = Lattice.cubic(5)

In [52]:
# Create a Lattice object with the grid shape (cubic in this case) and its parameters
my_lattice == my_lattice_2 == my_lattice_3

True

In [53]:
# Create a Structure object from the information of the lattice (Lattice) and the site (atoms and coordinates)
# Note that by default the coordinate system is fractional coordinate.
# Example: bcc (body-centered-cubic) iron
bcc_fe = Structure(Lattice.cubic(2.8), ["Fe", "Fe"], [[0, 0, 0], [0.5, 0.5, 0.5]])
print(bcc_fe)

Full Formula (Fe2)
Reduced Formula: Fe
abc   :   2.800000   2.800000   2.800000
angles:  90.000000  90.000000  90.000000
Sites (2)
  #  SP      a    b    c
---  ----  ---  ---  ---
  0  Fe    0    0    0
  1  Fe    0.5  0.5  0.5


In [54]:
# If you want to specify the coordinates in Cartesian coordinates, set the argument coords_are_cartesian = True.
bcc_fe_from_cart = Structure(Lattice.cubic(2.8), ["Fe", "Fe"], [[0, 0, 0], [1.4, 1.4, 1.4]],
                             coords_are_cartesian=True)
print(bcc_fe_from_cart)

Full Formula (Fe2)
Reduced Formula: Fe
abc   :   2.800000   2.800000   2.800000
angles:  90.000000  90.000000  90.000000
Sites (2)
  #  SP      a    b    c
---  ----  ---  ---  ---
  0  Fe    0    0    0
  1  Fe    0.5  0.5  0.5


In [55]:
# The two Structures will be the same
bcc_fe == bcc_fe_from_cart

True

In [56]:
# Information such as the volume of the grid can be retrieved as an attribute.
bcc_fe.volume

21.951999999999995

In [57]:
# You can create a Structure object by specifying a Space group.
bcc_fe = Structure.from_spacegroup("Im-3m", Lattice.cubic(2.8), ["Fe"], [[0, 0, 0]])
print(bcc_fe)

Full Formula (Fe2)
Reduced Formula: Fe
abc   :   2.800000   2.800000   2.800000
angles:  90.000000  90.000000  90.000000
Sites (2)
  #  SP      a    b    c
---  ----  ---  ---  ---
  0  Fe    0    0    0
  1  Fe    0.5  0.5  0.5


In [58]:
# In the case of NaCl, it is easier to define by specifying the space group.
nacl = Structure.from_spacegroup("Fm-3m", Lattice.cubic(5.692), ["Na+", "Cl-"],
                                 [[0, 0, 0], [0.5, 0.5, 0.5]])
print(nacl)


Full Formula (Na4 Cl4)
Reduced Formula: NaCl
abc   :   5.692000   5.692000   5.692000
angles:  90.000000  90.000000  90.000000
Sites (8)
  #  SP      a    b    c
---  ----  ---  ---  ---
  0  Na+   0    0    0
  1  Na+   0    0.5  0.5
  2  Na+   0.5  0    0.5
  3  Na+   0.5  0.5  0
  4  Cl-   0.5  0.5  0.5
  5  Cl-   0.5  0    0
  6  Cl-   0    0.5  0
  7  Cl-   0    0    0.5


In [59]:
# Get the space group name and space group number from the Structure object
nacl.get_space_group_info()

('Fm-3m', 225)

Generating Supercell

In [60]:
polonium = Structure(Lattice.cubic(3.4), ["Po"], [[0.0, 0.0, 0.0]])
print(polonium)

Full Formula (Po1)
Reduced Formula: Po
abc   :   3.400000   3.400000   3.400000
angles:  90.000000  90.000000  90.000000
Sites (1)
  #  SP      a    b    c
---  ----  ---  ---  ---
  0  Po      0    0    0


In [61]:
# Specify the size of the supercell in the tuple and multiply it by the Structure object
# Example: Generate a 2x2x2 supercell
supercell = polonium * (2, 2, 2)
print(supercell)

Full Formula (Po8)
Reduced Formula: Po
abc   :   6.800000   6.800000   6.800000
angles:  90.000000  90.000000  90.000000
Sites (8)
  #  SP      a    b    c
---  ----  ---  ---  ---
  0  Po    0    0    0
  1  Po    0    0    0.5
  2  Po    0    0.5  0
  3  Po    0    0.5  0.5
  4  Po    0.5  0    0
  5  Po    0.5  0    0.5
  6  Po    0.5  0.5  0
  7  Po    0.5  0.5  0.5


Structural changes of BaTiO3

In [62]:
from google.colab import files
uploaded = files.upload() # *.cif

Saving BaTiO3.cif to BaTiO3.cif


In [63]:
# Read data from cif file
BaTiO3=Structure.from_file("BaTiO3.cif")
print(BaTiO3.get_space_group_info())
print(BaTiO3)

('R3m', 160)
Full Formula (Ba1 Ti1 O3)
Reduced Formula: BaTiO3
abc   :   4.077159   4.077159   4.077159
angles:  89.699022  89.699022  89.699022
Sites (5)
  #  SP           a         b         c
---  ----  --------  --------  --------
  0  Ba    0.497155  0.497155  0.497155
  1  Ti    0.982209  0.982209  0.982209
  2  O     0.524065  0.012736  0.012736
  3  O     0.012736  0.012736  0.524065
  4  O     0.012736  0.524065  0.012736


In [64]:
# Replace Ba atom with Mg atom
BaTiO3.replace(0,'Mg')
print(BaTiO3)

Full Formula (Mg1 Ti1 O3)
Reduced Formula: MgTiO3
abc   :   4.077159   4.077159   4.077159
angles:  89.699022  89.699022  89.699022
Sites (5)
  #  SP           a         b         c
---  ----  --------  --------  --------
  0  Mg    0.497155  0.497155  0.497155
  1  Ti    0.982209  0.982209  0.982209
  2  O     0.524065  0.012736  0.012736
  3  O     0.012736  0.012736  0.524065
  4  O     0.012736  0.524065  0.012736


In [65]:
# Generate a 1x1x4 supercell
BaTiO3=BaTiO3*(1,1,4)
print(BaTiO3)

Full Formula (Mg4 Ti4 O12)
Reduced Formula: MgTiO3
abc   :   4.077159   4.077159  16.308637
angles:  89.699022  89.699022  89.699022
Sites (20)
  #  SP           a         b         c
---  ----  --------  --------  --------
  0  Mg    0.497155  0.497155  0.124289
  1  Mg    0.497155  0.497155  0.374289
  2  Mg    0.497155  0.497155  0.624289
  3  Mg    0.497155  0.497155  0.874289
  4  Ti    0.982209  0.982209  0.245552
  5  Ti    0.982209  0.982209  0.495552
  6  Ti    0.982209  0.982209  0.745552
  7  Ti    0.982209  0.982209  0.995552
  8  O     0.524065  0.012736  0.003184
  9  O     0.524065  0.012736  0.253184
 10  O     0.524065  0.012736  0.503184
 11  O     0.524065  0.012736  0.753184
 12  O     0.012736  0.012736  0.131016
 13  O     0.012736  0.012736  0.381016
 14  O     0.012736  0.012736  0.631016
 15  O     0.012736  0.012736  0.881016
 16  O     0.012736  0.524065  0.003184
 17  O     0.012736  0.524065  0.253184
 18  O     0.012736  0.524065  0.503184
 19  O     0.012